/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekjokitugas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author ASUS
 */
public class Pelanggan extends javax.swing.JFrame {

    /**
     * Creates new form Pelanggan
     */
 
    public Pelanggan() {
        initComponents();
        tampilData();
    }
    public void tampilData(){
        DefaultTableModel model = new DefaultTableModel();

model.addColumn("ID Pelanggan");
model.addColumn("Nama");
model.addColumn("No Telepon");
model.addColumn("Instansi");

try {

    Connection conn = Koneksi.getKoneksi();

    String sql = "SELECT * FROM tbl_pelanggan";

    PreparedStatement pst = conn.prepareStatement(sql);

    ResultSet rs = pst.executeQuery();

    while (rs.next()) {

        model.addRow(new Object[]{
            rs.getString("id_pelanggan"),
            rs.getString("nama"),
            rs.getString("no_telepon"),
            rs.getString("instansi")
        });

    }

    tblDataPelanggan.setModel(model);

} catch (Exception e) {

    JOptionPane.showMessageDialog(null, e);

}

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        kembali = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        idpelanggan = new javax.swing.JTextField();
        namapelanggan = new javax.swing.JTextField();
        notelepon = new javax.swing.JTextField();
        instansi = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataPelanggan = new javax.swing.JTable();
        carinama = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATA PELANGGAN");

        jLabel2.setText("ID Pelanggan");

        jLabel4.setText("Nama");

        jLabel5.setText("No Telepon");

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        jLabel6.setText("Intansi");

        idpelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpelangganActionPerformed(evt);
            }
        });

        notelepon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noteleponActionPerformed(evt);
            }
        });

        tblDataPelanggan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Pelanggan", "Nama", "No Telepon", "Instansi"
            }
        ));
        tblDataPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataPelangganMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDataPelanggan);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(simpan)
                                .addGap(18, 18, 18)
                                .addComponent(edit))
                            .addComponent(jLabel2)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(hapus)
                                .addGap(18, 18, 18)
                                .addComponent(cari)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(carinama, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                                .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(notelepon)
                                        .addComponent(idpelanggan)
                                        .addComponent(instansi, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(108, 108, 108))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(164, 164, 164)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24)
                        .addComponent(idpelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(namapelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(notelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(instansi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(edit)
                    .addComponent(hapus)
                    .addComponent(cari)
                    .addComponent(kembali)
                    .addComponent(carinama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 293, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try {
            
            Connection conn = Koneksi.getKoneksi();
            
            String sql = "DELETE FROM tbl_pelanggan WHERE id_pelanggan=?";
            
            PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, idpelanggan.getText());
            
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
            
            tampilData();
            
}catch (Exception e) {
    JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
    Menu mn = new Menu();
    mn.setVisible(true);

    this.dispose();



    }//GEN-LAST:event_kembaliActionPerformed

    private void idpelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpelangganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpelangganActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
try {
     Connection conn = Koneksi.getKoneksi();

     String sql = "INSERT INTO tbl_pelanggan(nama,no_telepon,instansi) VALUES (?,?,?)";
     
     PreparedStatement pst = conn.prepareStatement(sql);
     
     pst.setString(1, namapelanggan.getText());
     pst.setString(2, notelepon.getText());
     pst.setString(3, instansi.getText());
     
     pst.executeUpdate();
     
     JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
     
     tampilData();
     
     } catch (Exception e) {
    
    JOptionPane.showMessageDialog(null, e);
}

    }//GEN-LAST:event_simpanActionPerformed

    private void noteleponActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noteleponActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noteleponActionPerformed

    private void tblDataPelangganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataPelangganMouseClicked
        // TODO add your handling code here:
        int baris = tblDataPelanggan.getSelectedRow();
        
        idpelanggan.setText(tblDataPelanggan.getValueAt(baris,0).toString());
        namapelanggan.setText(tblDataPelanggan.getValueAt(baris, 1).toString());
        notelepon.setText(tblDataPelanggan.getValueAt(baris, 2).toString());
        instansi.setText(tblDataPelanggan.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_tblDataPelangganMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {

    Connection conn = Koneksi.getKoneksi();

    String sql = "UPDATE tbl_pelanggan SET nama=?, no_telepon=?, instansi=? WHERE id_pelanggan=?";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, namapelanggan.getText());
    pst.setString(2, notelepon.getText());
    pst.setString(3, instansi.getText());
    pst.setString(4, idpelanggan.getText());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Data Berhasil Diubah");

    tampilData();

} catch (Exception e) {

    JOptionPane.showMessageDialog(null, e);

}
    }//GEN-LAST:event_editActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:
     try {

    Connection conn = Koneksi.getKoneksi();

    DefaultTableModel model = (DefaultTableModel) tblDataPelanggan.getModel();

    model.setRowCount(0);

    String sql = "SELECT * FROM tbl_pelanggan WHERE nama LIKE ?";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, "%" + carinama.getText() + "%");

    ResultSet rs = pst.executeQuery();

    while (rs.next()) {

        model.addRow(new Object[]{
            rs.getString("id_pelanggan"),
            rs.getString("nama"),
            rs.getString("no_telepon"),
            rs.getString("instansi")
        });

    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(null, e);

}
    }//GEN-LAST:event_cariActionPerformed

   

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pelanggan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pelanggan().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JTextField carinama;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idpelanggan;
    private javax.swing.JTextField instansi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField namapelanggan;
    private javax.swing.JTextField notelepon;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tblDataPelanggan;
    // End of variables declaration//GEN-END:variables
}