/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekjokitugas;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Pembayaran extends javax.swing.JFrame {

    /**
     * Creates new form Pembayaran
     */
    public Pembayaran() {
        initComponents();
        
        tampilPesanan();
        tampilData();
    }
        public void tampilPesanan(){   

    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "SELECT * FROM tbl_pesanan";

        PreparedStatement pst = conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            cbPesanan.addItem(
                rs.getString("id_pesanan") + " - " +
                rs.getString("mata_kuliah")
            );

        }

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

        }
            }
        public void tampilData(){

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID Pembayaran");
    model.addColumn("Pesanan");
    model.addColumn("Metode Pembayaran");
    model.addColumn("Jumlah Bayar");
    model.addColumn("Tanggal Bayar");
    model.addColumn("Status Pembayaran");

    tblDataPembayaran.setModel(model);

    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "SELECT pb.id_pembayaran, ps.mata_kuliah, "
                + "pb.metode_pembayaran, pb.jumlah_bayar, "
                + "pb.tanggal_bayar, pb.status_pembayaran "
                + "FROM tbl_pembayaran pb "
                + "JOIN tbl_pesanan ps ON pb.id_pesanan = ps.id_pesanan";

        PreparedStatement pst = conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        while(rs.next()){

            model.addRow(new Object[]{

                rs.getString("id_pembayaran"),
                rs.getString("mata_kuliah"),
                rs.getString("metode_pembayaran"),
                rs.getString("jumlah_bayar"),
                rs.getString("tanggal_bayar"),
                rs.getString("status_pembayaran")

            });

        }

    } catch (Exception e){

        JOptionPane.showMessageDialog(null, e);
    }
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        caripesanan = new javax.swing.JTextField();
        kembali = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataPesanan = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        idpembayaran = new javax.swing.JTextField();
        cbPesanan = new javax.swing.JComboBox<>();
        cbMetode = new javax.swing.JComboBox<>();
        jumlahbayar = new javax.swing.JTextField();
        tanggalbayar = new javax.swing.JTextField();
        cbStatusPembayaran = new javax.swing.JComboBox<>();
        simpan1 = new javax.swing.JButton();
        edit1 = new javax.swing.JButton();
        hapus1 = new javax.swing.JButton();
        cari1 = new javax.swing.JButton();
        caripembayaran = new javax.swing.JTextField();
        kembali1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDataPembayaran = new javax.swing.JTable();

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        tblDataPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Layanan", "Nama Layanan", "Harga", "Deskripsi"
            }
        ));
        tblDataPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataPesananMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDataPesanan);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATA PEMBAYARAN");

        jLabel2.setText("ID Pembayaran");

        jLabel3.setText("Pesanan");

        jLabel4.setText("Metode Pembayaran");

        jLabel5.setText("Jumlah Bayar");

        jLabel6.setText("Tanggal Bayar");

        jLabel7.setText("Status Pembayaran");

        idpembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idpembayaranActionPerformed(evt);
            }
        });

        cbPesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbPesananActionPerformed(evt);
            }
        });

        cbMetode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Transfer Bank", "E-Wallet", "Cash" }));

        cbStatusPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DP", "Lunas", "Belum Lunas" }));
        cbStatusPembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbStatusPembayaranActionPerformed(evt);
            }
        });

        simpan1.setText("Simpan");
        simpan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan1ActionPerformed(evt);
            }
        });

        edit1.setText("Edit");
        edit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit1ActionPerformed(evt);
            }
        });

        hapus1.setText("Hapus");
        hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus1ActionPerformed(evt);
            }
        });

        cari1.setText("Cari");
        cari1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cari1ActionPerformed(evt);
            }
        });

        kembali1.setText("Kembali");
        kembali1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembali1ActionPerformed(evt);
            }
        });

        tblDataPembayaran.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID Pembayaran", "Pesanan", "Metode Pembayaran", "Jumlah Bayar", "Tanggal Bayar", "Status Pembayaran"
            }
        ));
        tblDataPembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataPembayaranMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblDataPembayaran);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbMetode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jumlahbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tanggalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbStatusPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 548, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpan1)
                        .addGap(18, 18, 18)
                        .addComponent(edit1)
                        .addGap(18, 18, 18)
                        .addComponent(hapus1)
                        .addGap(18, 18, 18)
                        .addComponent(cari1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(caripembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kembali1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idpembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbMetode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jumlahbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tanggalbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cbStatusPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan1)
                    .addComponent(edit1)
                    .addComponent(hapus1)
                    .addComponent(cari1)
                    .addComponent(kembali1)
                    .addComponent(caripembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addGap(13, 13, 13))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idpembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idpembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idpembayaranActionPerformed

    private void cbStatusPembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbStatusPembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbStatusPembayaranActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        

        
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_hapusActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:

        
    }//GEN-LAST:event_cariActionPerformed

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        Menu mn = new Menu();
        mn.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void tblDataPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataPesananMouseClicked
        // TODO add your handling code here:
        int baris = tblDataPembayaran.getSelectedRow();

idpembayaran.setText(
    tblDataPembayaran.getValueAt(baris, 0).toString()
);

jumlahbayar.setText(
    tblDataPembayaran.getValueAt(baris, 3).toString()
);

tanggalbayar.setText(
    tblDataPembayaran.getValueAt(baris, 4).toString()
);

cbMetode.setSelectedItem(
    tblDataPembayaran.getValueAt(baris, 2).toString()
);

cbStatusPembayaran.setSelectedItem(
    tblDataPembayaran.getValueAt(baris, 5).toString()
);
    }//GEN-LAST:event_tblDataPesananMouseClicked

    private void simpan1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan1ActionPerformed
try {

    Connection conn = Koneksi.getKoneksi();

    String pesanan = cbPesanan.getSelectedItem().toString();

    String idPesanan = pesanan.split(" - ")[0];

    String sql = "INSERT INTO tbl_pembayaran(id_pesanan,metode_pembayaran,jumlah_bayar,tanggal_bayar,status_pembayaran) VALUES (?,?,?,?,?)";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, idPesanan);
    pst.setString(2, cbMetode.getSelectedItem().toString());
    pst.setString(3, jumlahbayar.getText());
    pst.setString(4, tanggalbayar.getText());
    pst.setString(5, cbStatusPembayaran.getSelectedItem().toString());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Data Pembayaran Berhasil Disimpan");

    tampilData();

} catch (Exception e) {

    JOptionPane.showMessageDialog(null, e);

}       
    }//GEN-LAST:event_simpan1ActionPerformed

    private void edit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit1ActionPerformed
        // TODO add your handling code here:
    try {

        Connection conn = Koneksi.getKoneksi();

        String pesanan = cbPesanan.getSelectedItem().toString();

        String idPesanan = pesanan.split(" - ")[0];

        String sql = "UPDATE tbl_pembayaran SET id_pesanan=?, metode_pembayaran=?, jumlah_bayar=?, tanggal_bayar=?, status_pembayaran=? WHERE id_pembayaran=?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, idPesanan);
        pst.setString(2, cbMetode.getSelectedItem().toString());
        pst.setString(3, jumlahbayar.getText());
        pst.setString(4, tanggalbayar.getText());
        pst.setString(5, cbStatusPembayaran.getSelectedItem().toString());
        pst.setString(6, idpembayaran.getText());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data Pembayaran Berhasil Diubah");

        tampilData();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }
    }//GEN-LAST:event_edit1ActionPerformed

    private void hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus1ActionPerformed
        // TODO add your handling code here:
    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "DELETE FROM tbl_pembayaran WHERE id_pembayaran=?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, idpembayaran.getText());

        pst.executeUpdate();

        JOptionPane.showMessageDialog(null, "Data Pembayaran Berhasil Dihapus");

        tampilData();

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }
    }//GEN-LAST:event_hapus1ActionPerformed

    private void cari1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cari1ActionPerformed
        // TODO add your handling code here:
    try {

        Connection conn = Koneksi.getKoneksi();

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID Pembayaran");
        model.addColumn("Pesanan");
        model.addColumn("Metode Pembayaran");
        model.addColumn("Jumlah Bayar");
        model.addColumn("Tanggal Bayar");
        model.addColumn("Status Pembayaran");

        String sql = "SELECT pb.id_pembayaran, ps.mata_kuliah, "
                + "pb.metode_pembayaran, pb.jumlah_bayar, "
                + "pb.tanggal_bayar, pb.status_pembayaran "
                + "FROM tbl_pembayaran pb "
                + "JOIN tbl_pesanan ps ON pb.id_pesanan = ps.id_pesanan "
                + "WHERE ps.mata_kuliah LIKE ? "
                + "OR pb.metode_pembayaran LIKE ? "
                + "OR pb.status_pembayaran LIKE ?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, "%" + caripembayaran.getText() + "%");
        pst.setString(2, "%" + caripembayaran.getText() + "%");
        pst.setString(3, "%" + caripembayaran.getText() + "%");

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getString("id_pembayaran"),
                rs.getString("mata_kuliah"),
                rs.getString("metode_pembayaran"),
                rs.getString("jumlah_bayar"),
                rs.getString("tanggal_bayar"),
                rs.getString("status_pembayaran")

            });

        }

        tblDataPembayaran.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }
    }//GEN-LAST:event_cari1ActionPerformed

    private void kembali1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembali1ActionPerformed
        // TODO add your handling code here:
        Menu mn = new Menu();
        mn.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_kembali1ActionPerformed

    private void tblDataPembayaranMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataPembayaranMouseClicked
        // TODO add your handling code here:
        
        int baris = tblDataPembayaran.getSelectedRow();

idpembayaran.setText(
    tblDataPembayaran.getValueAt(baris, 0).toString()
);

jumlahbayar.setText(
    tblDataPembayaran.getValueAt(baris, 3).toString()
);

tanggalbayar.setText(
    tblDataPembayaran.getValueAt(baris, 4).toString()
);

cbMetode.setSelectedItem(
    tblDataPembayaran.getValueAt(baris, 2).toString()
);

cbStatusPembayaran.setSelectedItem(
    tblDataPembayaran.getValueAt(baris, 5).toString()
);
    }//GEN-LAST:event_tblDataPembayaranMouseClicked

    private void cbPesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbPesananActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbPesananActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JButton cari1;
    private javax.swing.JTextField caripembayaran;
    private javax.swing.JTextField caripesanan;
    private javax.swing.JComboBox<String> cbMetode;
    private javax.swing.JComboBox<String> cbPesanan;
    private javax.swing.JComboBox<String> cbStatusPembayaran;
    private javax.swing.JButton edit;
    private javax.swing.JButton edit1;
    private javax.swing.JButton hapus;
    private javax.swing.JButton hapus1;
    private javax.swing.JTextField idpembayaran;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jumlahbayar;
    private javax.swing.JButton kembali;
    private javax.swing.JButton kembali1;
    private javax.swing.JButton simpan;
    private javax.swing.JButton simpan1;
    private javax.swing.JTextField tanggalbayar;
    private javax.swing.JTable tblDataPembayaran;
    private javax.swing.JTable tblDataPesanan;
    // End of variables declaration//GEN-END:variables
}
