/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projekjokitugas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ASUS
 */
public class Pesanan extends javax.swing.JFrame {

    /**
     * Creates new form Pesanan
     */
    public Pesanan() {
        initComponents();
        
        tampilPelanggan();
        tampilLayanan();
        tampilData();
    }
    
    public void tampilPelanggan(){
        try {

    Connection conn = Koneksi.getKoneksi();

    String sql = "SELECT * FROM tbl_pelanggan";

    PreparedStatement pst = conn.prepareStatement(sql);

    ResultSet rs = pst.executeQuery();

    while (rs.next()) {

        cbPelanggan.addItem(
            rs.getString("id_pelanggan") + " - " +
            rs.getString("nama")
        );

    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(null, e);

}
    }
    
    public void tampilLayanan(){
        try {

    Connection conn = Koneksi.getKoneksi();

    String sql = "SELECT * FROM tbl_pelayanan";

    PreparedStatement pst = conn.prepareStatement(sql);

    ResultSet rs = pst.executeQuery();

    while (rs.next()) {

        cbLayanan.addItem(
            rs.getString("id_pelayanan") + " - " +
            rs.getString("nama_layanan")
        );

    }

} catch (Exception e) {

    JOptionPane.showMessageDialog(null, e);

}
    }
    public void tampilData(){

    DefaultTableModel model = new DefaultTableModel();

    model.addColumn("ID Pesanan");
    model.addColumn("Pelanggan");
    model.addColumn("Layanan");
    model.addColumn("Mata Kuliah");
    model.addColumn("Deadline");
    model.addColumn("Total Harga");
    model.addColumn("Status");
    model.addColumn("Catatan");

    tblDataPesanan.setModel(model);

    try {

        Connection conn = Koneksi.getKoneksi();

        String sql = "SELECT p.id_pesanan, pl.nama, l.nama_layanan, "
                + "p.mata_kuliah, p.deadline, p.total_harga, "
                + "p.status, p.catatan "
                + "FROM tbl_pesanan p "
                + "JOIN tbl_pelanggan pl ON p.id_pelanggan = pl.id_pelanggan "
                + "JOIN tbl_pelayanan l ON p.id_layanan = l.id_pelayanan";

        PreparedStatement pst = conn.prepareStatement(sql);

        ResultSet rs = pst.executeQuery();

        while(rs.next()){

            model.addRow(new Object[]{

                rs.getString("id_pesanan"),
                rs.getString("nama"),
                rs.getString("nama_layanan"),
                rs.getString("mata_kuliah"),
                rs.getString("deadline"),
                rs.getString("total_harga"),
                rs.getString("status"),
                rs.getString("catatan")

            });

        }

    } catch (Exception e){

        JOptionPane.showMessageDialog(null, e);

    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        idpesanan = new javax.swing.JTextField();
        cbPelanggan = new javax.swing.JComboBox<>();
        cbLayanan = new javax.swing.JComboBox<>();
        matakuliah = new javax.swing.JTextField();
        deadline = new javax.swing.JTextField();
        totalharga = new javax.swing.JTextField();
        cbStatus = new javax.swing.JComboBox<>();
        catatan = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDataPesanan = new javax.swing.JTable();
        kembali = new javax.swing.JButton();
        caripesanan = new javax.swing.JTextField();
        cari = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        simpan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DATA PESANAN");

        jLabel2.setText("ID Pesanan");

        jLabel3.setText("Pelanggan");

        jLabel4.setText("Layanan");

        jLabel5.setText("Mata Kuliah");

        jLabel6.setText("Deadline");

        jLabel7.setText("Total Harga");

        jLabel8.setText("Status");

        jLabel9.setText("Catatan");

        cbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Proses", "Selesai", "Dibatalkan" }));

        catatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catatanActionPerformed(evt);
            }
        });

        tblDataPesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Layanan", "Nama Layanan", "Harga", "Deskripsi"
            }
        ));
        tblDataPesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDataPesananMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDataPesanan);

        kembali.setText("Kembali");
        kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kembaliActionPerformed(evt);
            }
        });

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        simpan.setText("Simpan");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addGap(353, 353, 353)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idpesanan)
                                    .addComponent(cbPelanggan, 0, 90, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbLayanan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(matakuliah)
                                    .addComponent(deadline)
                                    .addComponent(totalharga)
                                    .addComponent(catatan))))
                        .addGap(46, 46, 46))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(simpan)
                        .addGap(18, 18, 18)
                        .addComponent(edit)
                        .addGap(18, 18, 18)
                        .addComponent(hapus)
                        .addGap(18, 18, 18)
                        .addComponent(cari)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(caripesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kembali, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(201, 201, 201)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(idpesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbPelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbLayanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(matakuliah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(deadline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(totalharga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(catatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpan)
                    .addComponent(edit)
                    .addComponent(hapus)
                    .addComponent(cari)
                    .addComponent(kembali)
                    .addComponent(caripesanan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void catatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catatanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_catatanActionPerformed

    private void tblDataPesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDataPesananMouseClicked
        // TODO add your handling code here:
        int baris = tblDataPesanan.getSelectedRow();
        idpesanan.setText(tblDataPesanan.getValueAt(baris,0).toString());
        matakuliah.setText(tblDataPesanan.getValueAt(baris,3).toString());
        deadline.setText(tblDataPesanan.getValueAt(baris,4).toString());
        totalharga.setText(tblDataPesanan.getValueAt(baris,5).toString());
        catatan.setText(tblDataPesanan.getValueAt(baris,7).toString());
        
String idPelanggan = tblDataPesanan.getValueAt(baris, 1).toString();

for (int i = 0; i < cbPelanggan.getItemCount(); i++) {

    String item = cbPelanggan.getItemAt(i);

    if (item.startsWith(idPelanggan + " - ")) {

        cbPelanggan.setSelectedIndex(i);
        break;

    }

}

String idLayanan = tblDataPesanan.getValueAt(baris, 2).toString();

for (int i = 0; i < cbLayanan.getItemCount(); i++) {

    String item = cbLayanan.getItemAt(i);

    if (item.startsWith(idLayanan + " - ")) {

        cbLayanan.setSelectedIndex(i);
        break;

    }

}

cbStatus.setSelectedItem(
    tblDataPesanan.getValueAt(baris, 6).toString()
);
        
    }//GEN-LAST:event_tblDataPesananMouseClicked

    private void kembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kembaliActionPerformed
        // TODO add your handling code here:
        Menu mn = new Menu();
        mn.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_kembaliActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        // TODO add your handling code here:

    try {

        Connection conn = Koneksi.getKoneksi();

        DefaultTableModel model = new DefaultTableModel();

        model.addColumn("ID Pesanan");
        model.addColumn("Pelanggan");
        model.addColumn("Layanan");
        model.addColumn("Mata Kuliah");
        model.addColumn("Deadline");
        model.addColumn("Total Harga");
        model.addColumn("Status");
        model.addColumn("Catatan");

        String sql = "SELECT p.id_pesanan, pl.nama, l.nama_layanan, "
                + "p.mata_kuliah, p.deadline, p.total_harga, "
                + "p.status, p.catatan "
                + "FROM tbl_pesanan p "
                + "JOIN tbl_pelanggan pl ON p.id_pelanggan = pl.id_pelanggan "
                + "JOIN tbl_pelayanan l ON p.id_layanan = l.id_pelayanan "
                + "WHERE pl.nama LIKE ? "
                + "OR l.nama_layanan LIKE ? "
                + "OR p.mata_kuliah LIKE ?";

        PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, "%" + caripesanan.getText() + "%");
        pst.setString(2, "%" + caripesanan.getText() + "%");
        pst.setString(3, "%" + caripesanan.getText() + "%");

        ResultSet rs = pst.executeQuery();

        while (rs.next()) {

            model.addRow(new Object[]{

                rs.getString("id_pesanan"),
                rs.getString("nama"),
                rs.getString("nama_layanan"),
                rs.getString("mata_kuliah"),
                rs.getString("deadline"),
                rs.getString("total_harga"),
                rs.getString("status"),
                rs.getString("catatan")

            });

        }

        tblDataPesanan.setModel(model);

    } catch (Exception e) {

        JOptionPane.showMessageDialog(null, e);

    }

    }//GEN-LAST:event_cariActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        try {

    Connection conn = Koneksi.getKoneksi();

    String sql = "DELETE FROM tbl_pelayanan WHERE id_pelayanan=?";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, idpesanan.getText());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");

    tampilData();

} catch (Exception e) {

    JOptionPane.showMessageDialog(null, e);

}   
    }//GEN-LAST:event_hapusActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        try {

    Connection conn = Koneksi.getKoneksi();

    String pelanggan = cbPelanggan.getSelectedItem().toString();
    String layanan = cbLayanan.getSelectedItem().toString();

    String idPelanggan = pelanggan.split(" - ")[0];
    String idLayanan = layanan.split(" - ")[0];

    String sql = "UPDATE tbl_pesanan SET id_pelanggan=?, id_layanan=?, mata_kuliah=?, deadline=?, total_harga=?, status=?, catatan=? WHERE id_pesanan=?";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, idPelanggan);
    pst.setString(2, idLayanan);
    pst.setString(3, matakuliah.getText());
    pst.setString(4, deadline.getText());
    pst.setString(5, totalharga.getText());
    pst.setString(6, cbStatus.getSelectedItem().toString());
    pst.setString(7, catatan.getText());
    pst.setString(8, idpesanan.getText());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Data Pesanan Berhasil Diubah");

    tampilData();

} catch (Exception e) {

    JOptionPane.showMessageDialog(null, e);

}
    }//GEN-LAST:event_editActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
try {

    Connection conn = Koneksi.getKoneksi();

    String pelanggan = cbPelanggan.getSelectedItem().toString();
    String layanan = cbLayanan.getSelectedItem().toString();

    String idPelanggan = pelanggan.split(" - ")[0];
    String idlayanan = layanan.split(" - ")[0];

    String sql = "INSERT INTO tbl_pesanan(id_pelanggan,id_layanan,mata_kuliah,deadline,total_harga,status,catatan) VALUES (?,?,?,?,?,?,?)";

    PreparedStatement pst = conn.prepareStatement(sql);

    pst.setString(1, idPelanggan);
    pst.setString(2, idlayanan);
    pst.setString(3, matakuliah.getText());
    pst.setString(4, deadline.getText());
    pst.setString(5, totalharga.getText());
    pst.setString(6, cbStatus.getSelectedItem().toString());
    pst.setString(7, catatan.getText());

    pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Data Pesanan Berhasil Disimpan");

    tampilData();

} catch (Exception e) {

    JOptionPane.showMessageDialog(null, e);

}
    }//GEN-LAST:event_simpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pesanan().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cari;
    private javax.swing.JTextField caripesanan;
    private javax.swing.JTextField catatan;
    private javax.swing.JComboBox<String> cbLayanan;
    private javax.swing.JComboBox<String> cbPelanggan;
    private javax.swing.JComboBox<String> cbStatus;
    private javax.swing.JTextField deadline;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JTextField idpesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton kembali;
    private javax.swing.JTextField matakuliah;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tblDataPesanan;
    private javax.swing.JTextField totalharga;
    // End of variables declaration//GEN-END:variables

}